# Config version for compatibility and deprecations
config-version = 2

# Start AeroSpace at login
start-at-login = true

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
# https://nikitabobko.github.io/AeroSpace/guide#layouts
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'vertical'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# A callback that runs every time binding mode changes
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
on-mode-changed = []

# List of workspaces that should stay alive even when they contain no windows,
# even when they are invisible.
# This config version is only available since 'config-version = 2'
# Fallback value (if you omit the key): persistent-workspaces = []
persistent-workspaces = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
]

# In TOML, single square brackets [] define a table (like a dictionary or map) 
# Nested Tables: Use dot notation within single brackets to create nested structures.
# E.g. [mode.main.binding]

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

# Key bindings
# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/commands#layout
# Switch to tiles layout. Toggle the layout orientation if already in tiles layout:
ctrl-alt-cmd-slash = 'layout tiles horizontal vertical'
# Switch to accordion layout. Toggle the layout orientation if already in accordion layout:
ctrl-alt-cmd-period = 'layout accordion horizontal vertical'
# Switch between floating and accordion layout
# FIX: somehow cannot swtich back to accordion or tiling layout once the window has become floating
# ctrl-alt-cmd-comma = 'layout floating accordion'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-cmd-s = 'focus left'
ctrl-alt-cmd-d = 'focus down'
ctrl-alt-cmd-e = 'focus up'
ctrl-alt-cmd-f = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-alt-cmd-left = 'move left'
ctrl-alt-cmd-down = 'move down'
ctrl-alt-cmd-up = 'move up'
ctrl-alt-cmd-right = 'move right'

ctrl-alt-cmd-z = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-alt-cmd-shift-minus = 'resize smart -50'
ctrl-alt-cmd-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-alt-cmd-1 = 'workspace 1'
ctrl-alt-cmd-2 = 'workspace 2'
ctrl-alt-cmd-3 = 'workspace 3'
ctrl-alt-cmd-4 = 'workspace 4'
ctrl-alt-cmd-5 = 'workspace 5'
ctrl-alt-cmd-6 = 'workspace 6'
ctrl-alt-cmd-7 = 'workspace 7'
ctrl-alt-cmd-8 = 'workspace 8'
ctrl-alt-cmd-9 = 'workspace 9'
ctrl-alt-cmd-0 = 'workspace 10'
ctrl-alt-cmd-minus = 'workspace 11'
ctrl-alt-cmd-equal = 'workspace 12'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-alt-cmd-f1 = 'move-node-to-workspace 1'
ctrl-alt-cmd-f2 = 'move-node-to-workspace 2'
ctrl-alt-cmd-f3 = 'move-node-to-workspace 3'
ctrl-alt-cmd-f4 = 'move-node-to-workspace 4'
ctrl-alt-cmd-f5 = 'move-node-to-workspace 5'
ctrl-alt-cmd-f6 = 'move-node-to-workspace 6'
ctrl-alt-cmd-f7 = 'move-node-to-workspace 7'
ctrl-alt-cmd-f8 = 'move-node-to-workspace 8'
ctrl-alt-cmd-f9 = 'move-node-to-workspace 9'
ctrl-alt-cmd-f10 = 'move-node-to-workspace 10'
ctrl-alt-cmd-f11 = 'move-node-to-workspace 11'
ctrl-alt-cmd-f12 = 'move-node-to-workspace 12'

ctrl-alt-cmd-j = 'focus-monitor left'
ctrl-alt-cmd-i = 'focus-monitor up'
ctrl-alt-cmd-k = 'focus-monitor down'
ctrl-alt-cmd-l = 'focus-monitor right'

# Home, end, pageup/down are not yet supported
# https://github.com/nikitabobko/AeroSpace/issues/748
# ctrl-alt-cmd-home = 'move-node-to-monitor left'
# ctrl-alt-cmd-pageup = 'move-node-to-monitor up'
# ctrl-alt-cmd-pagedown = 'move-node-to-monitor down'
# ctrl-alt-cmd-end = 'move-node-to-monitor right'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-alt-cmd-semicolon = 'mode misc'

# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.misc.binding]
esc = 'mode main'
r = ['reload-config', 'mode main']

j = ['move-node-to-monitor left', 'mode main']
i = ['move-node-to-monitor up', 'mode main']
k = ['move-node-to-monitor down', 'mode main']
l = ['move-node-to-monitor right', 'mode main']

# s = ['join-with left', 'mode main']
# d = ['join-with down', 'mode main']
# e = ['join-with up', 'mode main']
# f = ['join-with right', 'mode main']

semicolon = ['flatten-workspace-tree', 'mode main'] # reset layout

# Callbacks
# https://nikitabobko.github.io/AeroSpace/guide#callbacks
# https://nikitabobko.github.io/AeroSpace/goodies#popular-apps-ids
# Or use `aerospace list-apps` to find the app-id

# Arrays of Tables: [[fruit]] creates a table named "fruit," and repeating it
# adds new entries to an array, each becoming a distinct table element.

# Make all windows floats by default
# [[on-window-detected]]
# check-further-callbacks = true
# run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
if.during-aerospace-startup = true
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
if.during-aerospace-startup = true
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.window-title-regex-substring = 'obsidian'
if.during-aerospace-startup = true
check-further-callbacks = true
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
if.during-aerospace-startup = true
check-further-callbacks = true
run = 'move-node-to-workspace 12'

[[on-window-detected]]
if.window-title-regex-substring = 'spotify'
if.during-aerospace-startup = true
check-further-callbacks = true
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.window-title-regex-substring = 'protonvpn'
if.during-aerospace-startup = true
check-further-callbacks = true
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.window-title-regex-substring = 'discord'
if.during-aerospace-startup = true
check-further-callbacks = true
run = 'move-node-to-workspace 5'

# [[on-window-detected]]
# if.window-title-regex-substring = 'cursor'
