#!/usr/bin/env bash

set -eu
if [[ "$(file -Lb --mime-type "$1")" =~ ^image ]]; then
    kitty +kitten icat --transfer-mode file --stdin no --place "${2}x${3}@${4}x${5}" "${1}" < /dev/null > /dev/tty
    exit 1
fi