#!/usr/bin/env bash

set -eu

get_mimetype() {
    if [ -f "$1" ]; then
        file -Lb --mime-type "$1"  # Follom symlink + brief output only
    else
        echo "Error: File '$1' not found"
        return 1
    fi
}

MIME_TYPE=$(get_mimetype $fx)

if [[ $MIME_TYPE =~ ^image ]]; then
    imv $fx
    exit 0
elif [[ $MIME_TYPE =~ ^text || $MIME_TYPE = application/json ]]; then
    nvim $fx
    exit 0
elif [[ $MIME_TYPE =~ ^video ]]; then
    celluloid $fx
    exit 0
else
    xdg-open $fx
    exit 0
fi
