return {
  copilot_plugin = "lua",
  lf_plugin = "custom",
  notify_backend = "custom",
  terminal_plugin = false,
  filetree_plugin = false,
  telescope_over_fzflua = false,
  dap_plugins = false,
  diffview_plugin = false,
  chatgpt_plugin = false,
  ssr_plugin = false,
  illuminate_plugin = false,
  spectre_plugin = false,
  vgit_plugin = false,
  trouble_plugin = false,
  maximize_plugin = false,
  surround_plugin = false,
  tabline_plugin = "custom",
  statusline_plugin = "custom",
  treesitter_textobjects_plugin = "custom",
  nvim_dev_plugin = "neodev",
  neoconf_plugin = false,
  persist_plugin = "custom",
  autopairs_plugin = false,
  format_on_save = false,
  fzf_plugin = "custom",

  theme_opts = {
    debug = {
      enabled = false,
      toggle_colorizer = false,
      hide_defined_entries = false,
      show_non_ts_syntax_hl_only = false,
    },
  },
}
